appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Pp5hjgnUx2Zw6C6/Qe97JI9WnWuE0T6I68HYvQ+rx19eL6r66reKaxueDbg7u+rpa204NgoEJThpjylCeua7cyzfMSltKTKyX/X5rD9sjKATfN1elFWzu87mhALHERnFg4zCRvuLBsX0KCcAjLom+2M/ifWaz4oRDDovMU+ikHpCqABZuORM+FVuW7Yi2MSzo20p+Drfq9+NGidXbvb/XHmqblUbh22PbSKXnlHHIKDazodeDTM33mom/eAVUxzQewuL9GVMp8jlceLevWN1qGUm3teNuwci3Xi5MmVTvcUfSMkXTVw4i21YHGsI/O1CO3HheGqhwWMmK4pRgb9yGbEsjxFyxJY7I8dpOSqKI84SCozJh4kTyR8Ku1gvHhVcHFUlKFBQUQq1Q+i03EOaOXIbO9p29juwh8YKM6KG11Sh5pjkqgoddv0HWgqIZUSYXMZ4ISuw+PtQDuZ4yfFIqTbI2k6XrZCA3DqI+V0An5vMJ4hpOKaA/Pk8vR5wOgRzLaLRUjLo8h+1iHl5TEDIimjpFXzRlUBSc/k7YPjbUxe+U9216YgucUTYJeUB1WIDDBXF4w/qJo7qZKg2UKF63AQM+87AxyHe03XmnCehN/r1atF+fqmMn9EmpslqkMZhLtY5QqIP99J/Q2TosiT9eKkDx7I5Rw6BH5Si/hl3LOk=}
conda_forge_output_validation: true
