travis:
  secure:
    BINSTAR_TOKEN: hWX6JMUmSe8p9+nHhhuwQtNvXHl7jhDUflnctSNAQWBqHqne8dKlsA30DxKDyf63pyiSNG2DIJ5/F8Knwl++GEYMXBzC/KS8T/+/gAN3k0nVGfUuaDZut4GL2iAVUDpP+35gYzd9QG0h3Z+jQC1pY19I6v4sPFFHZx0nqV9fqKsrRgi+M65TLnv3cqEDaOyjfzveDpKz900wXqy2G/hgISoH0k5QWjjzLV8zdiVdP8thRqp12YeWJeqGP9RxSwMo3eG6vJlozaU1bxA4RyuiOowAZzLnac/3rZzIgXXQTa6qcTi+X7Lwi59t62hFVNQ3Gt9pZw3Lb/V6EnghXd6l/t2L25hqKfEs/BRVhUidMv22pUHKC7OmW0T54p9+vL9HqoGIKHHoeyAo9r8U7PDn1Ifayz6dY4NUiQCNfI6C+kaG/kV9c4LzGkiZKsfLvhKyXltSXVpL87JT0ya+NjIHuYF+yDypyuB7Ueop9NKHb1A6iiHwA9Nic5GqIYaS1JmP8qL+B4CoraWq3siK2mCbUGG+z8AQxLhqDFGKqZjPZgBmhJRprys333PsmxRMGTdL0FhaZri0lQhHpjs9LVmRdlr11/6bpFEVS4hgv9SqeyrZwUVDyo4ynvJG9cGvBbCWlmrFTK3lmLIFh2h+3LechtAD460NUM0IfZU/hrqA31U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
